# Functions

In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions ##

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [3]:
def triple(x):
    result = 3 * x
    return result

In [4]:
output = triple(4)
output

12

We can also assign a value to a name, and call the function on the name:

In [5]:
num = 4

In [6]:
triple(num)

12

## The Anatomy of a Function ##  
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
      return return_expression
```

## Functions are Type-Agnostic  ##

In [7]:
triple('ha')

'hahaha'

In [8]:
triple(np.arange(4))

array([0, 3, 6, 9])

- What does the following function do?
- What type of input does it take?
- What type of output does it produce?
- What's a good name for the function?

```python
def f(s):     
      return np.round(s / sum(s) * 100, 2)
```

In [9]:
def percent_of_total(arr):
    return np.round(arr / sum(arr) * 100, 2)

In [10]:
first_four=make_array(3,5,6,9)
first_four

array([3, 5, 6, 9])

In [11]:
arr_out = percent_of_total(first_four)
arr_out

array([ 13.04,  21.74,  26.09,  39.13])

In [12]:
percent_of_total(make_array(1, 213, 38))

array([  0.4 ,  84.52,  15.08])

In [13]:
percent_of_total('test')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Functions Can Take Multiple Arguments ###

### Practice

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

Write a function called hypotenuse that takes the lengths of the two legs of a right triangle and returns the length of the hypotenuse. You can use:

    ** 0.5

to calculate the square root of a number.

## Apply ##

In [14]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
ages

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

In [15]:
def name_and_birthyear(name, year):
    out_string = name + " was born in " + str(year) + "."
    return out_string

In [18]:
name_and_birthyear('Jim', 1985)

'Jim was born in 1985.'

In [19]:
# .apply allows you to specify a function and the *names* of columns in a table
# The specified function will be applied to each row of the table using inputs from the columns you specified
ages_and_years = ages.apply(name_and_birthyear, 'Person', 'Birth Year')
ages_and_years

array(['Jim was born in 1985.', 'Pam was born in 1988.',
       'Michael was born in 1967.', 'Creed was born in 1904.'],
      dtype='<U25')

In [20]:
ages_and_years.item(0)

'Jim was born in 1985.'

# Practice

1. Define a function named percent_increase that takes two inputs: small and big. The function returns the the *percent* increase from small to big. For example, if small = 200 and big = 210, then percent_increase(small, big) returns 5.

2. Apply this function to the Gross and Gross (Adjusted) columns of top_movies.

3. Attach this new column to the table.

In [5]:
top_movies = Table.read_table('top_movies_2017.csv').select("Title", "Gross", "Gross (Adjusted)")
top_movies

Title                            | Gross     | Gross (Adjusted)
Gone with the Wind               | 198676459 | 1796176700
Star Wars                        | 460998007 | 1583483200
The Sound of Music               | 158671368 | 1266072700
E.T.: The Extra-Terrestrial      | 435110554 | 1261085000
Titanic                          | 658672302 | 1204368000
The Ten Commandments             | 65500000  | 1164590000
Jaws                             | 260000000 | 1138620700
Doctor Zhivago                   | 111721910 | 1103564200
The Exorcist                     | 232906145 | 983226600
Snow White and the Seven Dwarves | 184925486 | 969010000
... (190 rows omitted)

In [20]:
def percent_increase(small, big):
    increase = round(((big / small) - 1) * 100)
    return increase

In [19]:
growth_ar = top_movies.apply(percent_increase, 'Gross', 'Gross (Adjusted)')
growth_ar

array([ 804,  243,  698,  190,   83, 1678,  338,  888,  322,  424,    3,
        513,  200, 1077,   14,  170,  103,   69,   87,  408,  217,  625,
        866,    8,  420,  112,  580,  263,   10,  946,   24,  362, 1152,
        161,   43,  513,  485,   53,  101,  111,  611,  934,  154, 1054,
        485,  408, 1516,   36, 1268,  454,  370,  123, 2515,   45,   44,
        370,    1,  476,   43, 1382,  641,  276,   43,   39,  149,   50,
         14,   74,  280,  185,  299,    0,    3, 1040,   57,  429,  274,
        998,  334,  317, 1967,  477,   54,  101,   94, 1678,   19,  934,
       1085,  338,  485,  165,    4,   53,  114,  114,   12,  110,    7,
       2122,   11,   47, 1791, 1118,   94,  123,   51,    9,   29,    6,
        111, 2515,   64,  137,   12,   73,   57,   29,   13,    2,   47,
         29,  135, 4345,   88,    0,  370,  364,  164,   84,   38,   38,
         29,   52,  115, 1714,   24,   12,   41,   24,  103,    0,  111,
        199,  576,  123,    4,  579,    8,    9,  260,   90, 1085,  202,
         29,  150,  104,    4,  110,  370,   12,   43,   59,  114,    2,
        121,   53,   10,    3,  101,    7,    8,  283,  202,   75,   19,
         47,   43,  582,   65,   57,  104,  474,  125,    3,   94,  111,
        127,   12,   19,  114,   53,  220,   17,  423,  230,    3,  115,
          4,  116])

In [22]:
top_movies = top_movies.with_column(
    'Growth', growth_ar
)
top_movies

Title                            | Gross     | Gross (Adjusted) | Growth
Gone with the Wind               | 198676459 | 1796176700       | 804
Star Wars                        | 460998007 | 1583483200       | 243
The Sound of Music               | 158671368 | 1266072700       | 698
E.T.: The Extra-Terrestrial      | 435110554 | 1261085000       | 190
Titanic                          | 658672302 | 1204368000       | 83
The Ten Commandments             | 65500000  | 1164590000       | 1678
Jaws                             | 260000000 | 1138620700       | 338
Doctor Zhivago                   | 111721910 | 1103564200       | 888
The Exorcist                     | 232906145 | 983226600        | 322
Snow White and the Seven Dwarves | 184925486 | 969010000        | 424
... (190 rows omitted)